SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('studentapp/',include('studentapp.urls')),
    path('facultyapp/',include('facultyapp.urls')),
]

facultyapp/urls.py
from django.urls import path, include
from . import views

app_name='facultyapp'
urlpatterns = [

    path('facultyhomepage/',views.FacultyHomePage,name="facultyhomepage"),
    path('add_course/',views.add_course,name="add_course"),
    path('view_course/',views.view_student_list,name="view"),
    path('view_marks/',views.post_marks,name="post_marks"),
    path('feedback/', views.submit_feedback, name='feedback'),
    path('feedback/list/', views.feedback_list, name='feedback_list'),
]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name='studentapp'
urlpatterns = [
path('studenthomepage/',views.StudentHomePage,name="studenthomepage"),
path('view_marks/',views.view_marks,name="marks"),
]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #D3D3D3;">
  <div class="container-fluid">
    <a class="navbar-brand" href = "{% url 'facultyapp:facultyhomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'facultyapp:facultyhomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception Handler</a></li>
              <li><a class="dropdown-item" href="{% url 'randompagecall' %}">random pager</a></li>
<li><a class="dropdown-item" href="{% url 'datetimepage' %}">date</a></li>
              <li><a class="dropdown-item" href="{% url 'add_task' %}">ll</a></li>
               <li><a class="dropdown-item" href="{% url 'calculatorpage' %}">Calculator</a></li>
               <li><a class="dropdown-item" href="{% url 'add_student' %}">add Student</a></li>
              <li><a class="dropdown-item" href="{% url 'student_list' %}">Student List</a></li>
              <li><a class="dropdown-item" href="{% url 'facultyapp:add_course' %}">add course</a></li>
              <li><a class="dropdown-item" href="{% url 'facultyapp:view' %}">view</a></li>
              <li><a class="dropdown-item" href="{% url 'facultyapp:post_marks' %}">post marks</a></li>
              <li><a class="dropdown-item" href="{% url 'facultyapp:feedback' %}">Submit Feedback</a></li>

              <li><a class="dropdown-item" href="{% url 'facultyapp:feedback_list' %}">feedback list</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">add</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>

    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
         <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>

          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'userloginpage' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>


</nav>

{% block body %}
{% endblock %}
</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #D3D3D3;">
  <div class="container-fluid">
    <a class="navbar-brand" href = "{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception Handler</a></li>
              <li><a class="dropdown-item" href="{% url 'randompagecall' %}">random pager</a></li>
<li><a class="dropdown-item" href="{% url 'datetimepage' %}">date</a></li>
              <li><a class="dropdown-item" href="{% url 'add_task' %}">To DO List</a></li>
               <li><a class="dropdown-item" href="{% url 'calculatorpage' %}">Calculator</a></li>
               <li><a class="dropdown-item" href="{% url 'add_student' %}">add Student</a></li>
              <li><a class="dropdown-item" href="{% url 'student_list' %}">Student List</a></li>
              <li><a class="dropdown-item" href="{% url 'add_contact' %}">contact manager</a></li>

            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>

    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
         <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>

          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'userloginpage' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>


</nav>

{% block body %}
{% endblock %}
</body>
</html>

templates/Navbar/StudentNavebar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #D3D3D3;">
  <div class="container-fluid">
    <a class="navbar-brand" href = "#">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'studentapp:studenthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">

               <li><a class="dropdown-item" href="{% url 'studentapp:marks' %}">Marks</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>

    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
         <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>

          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'userloginpage' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>


</nav>

{% block body %}
{% endblock %}
</body>
</html>